# Cloudflare Pages configuration
name = "shaiitech-dot-com"
pages_build_output_dir = "dist"
compatibility_date = "2024-09-26"

[build]
command = "npm run build"

[env.production]
compatibility_date = "2024-09-26"

[[env.production.routes]]
pattern = "*"